cardDB = {
  onodera: {
    name: "Onodera Ukinagawa",
    age: 16,
    gender: "female",
    personality: "Shy, tranquil, intelligent",
    likes: "Cooking, going out with friends, talking, loves to get your attention",
    dislikes: "Being alone, being ignored by you",
    rewards: "Exp, Coins, Onodera Memories badge",
    presents: "Cakes, ramen, manga books and cute clothes",
    rarity: "rare",
    cover: {
      small: "img/onodera.jpg",
      big: "img/onodera.jpg",
      portrait: "img/onodera.jpg",
    },
  },
  eva: {
    name: "Eva Williamson",
    age: 16,
    gender: "female",
    personality: "Lovely, distant, different from the standard, wellbehaved",
    likes: "Reading books, going to the library and hanging out with you, Onodera and Shiina",
    dislikes: "Being ignored, not being able to share memories with her friends for the purpose of her book",
    rewards: "Exp, Coins, Eva Memories badge",
    presents: "Books, ramen, noodles, surprises and cute underwear",
    rarity: "epic",
    cover: {
      small: "img/eva.jpg",
      big: "img/eva.jpg",
      portrait: "img/eva.jpg",
    },
  },
  shiina: {
    name: "Mashiro Shiina",
    age: 16,
    gender: "female",
    personality: "Cold, lovely, affectuous and different from the standard",
    likes: "Drawing, staying at home or going out with you only and chat with you",
    dislikes: "You not complimenting her draws, her ramend getting cold and you arriving late",
    rewards: "Exp, Coins, Shiina Memories badge",
    presents: "Videogames, sweets and cute clothes",
    rarity: "legend",
    cover: {
      small: "img/shiina.jpg",
      big: "img/shiina.jpg",
      portrait: "img/shiina.jpg",
    },
  },
  miuna: {
    name: "Shiotome Miuna",
    age: 16,
    gender: "female",
    personality: "lovely, shy, big-hearted",
    likes: "",
    dislikes: "",
    rewards: "Exp, Coins, Miuna Memory badge and Access to future exclusive content",
    presents: "Necklaces, things related to the sea, ramen",
    rarity: "epic",
    cover: {
      small: "img/miuna.jpg",
      big: "img/miuna.jpg",
      portrait: "img/miuna.jpg",
    },
  },
};
